package:
  format-version: "1.0.0"
  name: "gfx_apps_sam_9x60"
  version: "v3.12.0"
  type: "application"
  status: "production"

  dependencies:
    - name: "gfx"
      type: "package"
      version: "v3.14.0"
