configName: lcdc_rgba8888_mxt_9x60_wvga
folderName: blank_qs_9x60_ek_tm5000
format_version: v1.0
frameworkPath: ..\..\..\..\harmony3_dev
processor: SAM9X60
projectName: blank_quickstart_9x60_ek_wvga
settings:
  PackageFilter: bsp;core;core_apps_sam_9x60;core_apps_sam_a5d2;crypto;csp;csp_apps_sam_9x60;csp_apps_sam_a5d2;dev_packs;gfx;gfx_apps_sam_9x60;harmony-services;net;quick_docs;touch;usb;usb_apps_device
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAM9X6_DFP\1.7.85
